<template>
   <h1>
       FILTER
   </h1>
    <router-view v-slot="{ Component, route }">&ndash;&gt;
        <div :key="route.name">&ndash;&gt;
            <Component :is="Component" />&ndash;&gt;
        </div>&ndash;&gt;
    </router-view>&ndash;&gt;
   <v-form-designer></v-form-designer>
</template>
<!--
Codes Generated By VForm:
https://www.vform666.com
-->

<template>
    <el-form :model="formData" ref="vForm" :rules="rules" label-position="left" label-width="80px"
             size="default" @submit.prevent>
        <el-row>
            <el-col :span="8" class="grid-cell">
                <el-form-item label="name" prop="name">
                    <el-input v-model="formData.name" type="text" clearable></el-input>
                </el-form-item>
                <el-form-item label="price" prop="price">
                    <el-slider v-model="formData.price" :step="1" range></el-slider>
                </el-form-item>
                <el-form-item label="bathrooms" prop="bathrooms">
                    <el-input-number v-model="formData.bathrooms" class="full-width-input" controls-position="right"
                                     :min="-100000000000" :max="100000000000" :precision="0" :step="1"></el-input-number>
                </el-form-item>
                <el-form-item label="bedrooms" prop="bedrooms">
                    <el-input-number v-model="formData.bedrooms" class="full-width-input" controls-position="right"
                                     :min="-100000000000" :max="100000000000" :precision="0" :step="1"></el-input-number>
                </el-form-item>
                <el-form-item label="storeys" prop="storeys">
                    <el-input-number v-model="formData.storeys" class="full-width-input" controls-position="right"
                                     :min="-100000000000" :max="100000000000" :precision="0" :step="1"></el-input-number>
                </el-form-item>
                <el-form-item label="garages" prop="garages">
                    <el-input-number v-model="formData.garages" class="full-width-input" controls-position="right"
                                     :min="-100000000000" :max="100000000000" :precision="0" :step="1"></el-input-number>
                </el-form-item>
            </el-col>
            <el-col :span="16" class="grid-cell">
                <pre v-for="room in roomsList">
                    {{ room }}
                </pre>
            </el-col>
        </el-row>
    </el-form>

</template>

<script>
import {
    defineComponent,
    toRefs,
    reactive,
    getCurrentInstance,
    watch,
    ref
}
    from 'vue'
import axios from "axios";

export default defineComponent({
    components: {},
    props: {},
    setup() {
        const state = reactive({
            formData: {
                name: "",
                price: null,
                bathrooms: 0,
                bedrooms: 0,
                storeys: 0,
                garages: 0,
            },
            rules: {},
        })
        const instance = getCurrentInstance()
        const roomsList = ref(null)
        const submitForm = () => {
            instance.proxy.$refs['vForm'].validate(valid => {
                if (!valid) return
            })
        }
        const getRooms = async (filter) => {
            try {
                let params = new URLSearchParams(filter);
                // params.append()
                console.log(params.toString())
                roomsList.value = await axios.get("/api/search")
                // response.value = await axios.get("/api/search");
            } catch (error) {
                // Do something with the error
                console.log(error);
            }
        };
        const resetForm = () => {
            instance.proxy.$refs['vForm'].resetFields()
        }
        watch(state, function (o,n) {
            getRooms(n.formData)
            // console.log(n.formData)
        })
        return {
            ...toRefs(state),
            submitForm,
            resetForm
        }
    }
})
// watch()
</script>

<style lang="scss">
    @import '../css/el.scss';
</style>
